apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-helm
  namespace: cert-manager-system
spec:
  interval: 30m
  url: oci://quay.io/jetstack/charts/cert-manager
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "1.21.x"
    semverFilter: "^v?[0-9]+\\.[0-9]+\\.[0-9]+$"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager-system
spec:
  interval: 5m
  releaseName: cert-manager
  storageNamespace: cert-manager-system
  targetNamespace: cert-manager-system
  chartRef:
    kind: OCIRepository
    name: cert-manager-helm
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    crds:
      enabled: true
    clusterResourceNamespace: cert-manager-system
    dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
    dns01RecursiveNameserversOnly: true
