apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 30m
  url: https://kyverno.github.io/kyverno

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  chart:
    spec:
      chart: kyverno
      version: "3.9.*"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno-system
  releaseName: kyverno
  targetNamespace: kyverno-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m
  values:
    global:
      nodeSelector:
        node-role.kubernetes.io/general: ""
    cleanupController:
      enabled: false
    reportsController:
      enabled: false
    features:
      admissionReports:
        enabled: false
      aggregateReports:
        enabled: false
      policyReports:
        enabled: false
      validatingAdmissionPolicyReports:
        enabled: false
