apiVersion: v1
kind: Namespace
metadata:
  name: grafana-system
  labels:
    oatlabs.oatmilk.work/gateway-access: "true"

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana-system
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana-system
spec:
  chart:
    spec:
      chart: grafana-operator
      version: "5.25.*"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana-system
  releaseName: grafana-operator
  targetNamespace: grafana-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m
  values:
    namespaceScope: false
    nodeSelector:
      node-role.kubernetes.io/observability: ""
    tolerations:
      - key: node-role.kubernetes.io/observability
        operator: Exists
        effect: NoSchedule
