apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-secret-vars
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: platform-secret-vars
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: ${OP_VAULT_GRAFANA_ADMIN_USER}
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: ${OP_VAULT_GRAFANA_ADMIN_PASSWORD}
