apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
  podMetricsEndpoints:
    - targetPort: 19001
      path: /stats/prometheus
      interval: 30s
