apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana-system
  labels:
    dashboards: grafana
spec:
  config:
    server:
      root_url: https://grafana.${CLUSTER_ZONE}
    security:
      admin_user: ${GRAFANA_ADMIN_USER}
      admin_password: ${GRAFANA_ADMIN_PASSWORD}
      cookie_secure: "true"
    auth.anonymous:
      enabled: "false"
    users:
      viewers_can_edit: "false"
    analytics:
      reporting_enabled: "false"
      check_for_updates: "false"
    smtp:
      enabled: "true"
      host: ${GRAFANA_SMTP_HOST}
      user: ${GRAFANA_SMTP_USER}
      from_address: ${GRAFANA_SMTP_FROM_ADDRESS}
      from_name: Grafana
      startTLS_policy: MandatoryStartTLS
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/observability: ""
          tolerations:
            - key: node-role.kubernetes.io/observability
              operator: Exists
              effect: NoSchedule
          containers:
            - name: grafana
              env:
                - name: GF_SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-smtp-secret
                      key: password
              resources:
                requests:
                  cpu: 50m
                  memory: 192Mi
                limits:
                  memory: 384Mi
