apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-certificate
  namespace: default
spec:
  secretName: cluster-certificate-key
  secretTemplate:
    labels:
      cnpg.io/reload: ""
      oatlabs.oatmilk.work/pooler-restart: "true"
  usages:
    - server auth
  dnsNames:
    - '*.${CLUSTER_ZONE}'
    - '${CLUSTER_ZONE}'
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
