apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zone-certificate
  namespace: ${PLATFORM_NAMESPACE}
spec:
  secretName: zone-certificate-tls
  secretTemplate:
    labels:
      cnpg.io/reload: ""
      oatlabs.oatmilk.work/pooler-restart: "true"
  usages:
    - server auth
  dnsNames:
    - '*.${CLUSTER_ZONE}'
    - '${CLUSTER_ZONE}'
  issuerRef:
    name: cluster-issuer-${ACME_ENV}
    kind: ClusterIssuer
    group: cert-manager.io
