apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: ${ENVOY_REPLICAS}
        pod:
          topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
              nodeTaintsPolicy: Honor
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: envoy
              matchLabelKeys:
                - gateway.envoyproxy.io/owning-gateway-name
                - gateway.envoyproxy.io/owning-gateway-namespace
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      envoyPDB:
        maxUnavailable: 1

